# Generated by Django 2.2.24 on 2021-12-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20211214_2113'),
        ('authnapp', '0006_auto_20211208_1828'),
    ]

    operations = [
    ]
